### ISSUE TITLE
Button click does not seem to work

### ISSUE THREAD

**Issue by silvanshade** [sardonicism-04/discord-rich-presence#16]
I'm trying to use this library for a custom presence app and although I can get buttons to show up in the presence, clicking on them seems to do nothing. No browser window opens or anything like that.

I have only tested this on macos with Discord client version `0.0.268`.

Just for some concrete examples, I've tried several different urls, such as `Button::new("google", "https://google.com")` and `Button::new("steam", "https://steampowered.com")`.

Can you confirm that button clicks are currently working as intended? Any ideas on what the problem might be?

**Comment by Rayrsn** [comment]
You can't click on your own buttons, if others can click on them and it opens the url then it means it's working

**Comment by silvanshade** [comment]
> You can't click on your own buttons, if others can click on them and it opens the url then it means it's working

Ah, that would explain it then. Thanks for the response!

**Comment by silvanshade** [comment]
Just to add a note to this: you can also test that the buttons work by checking the presence on Discord on mobile (where the buttons are clickable, for your own profile). At least this works on iOS. It's a little strange that it does't work on the desktop client and that the buttons aren't simply disabled or something.
